### ISSUE TITLE
White lock screen

### ISSUE THREAD

**Issue by shazow** [attente/dotfiles#1]
Your monitors are blinding white while you're away, probably not the best for your screens.

Also make your screens turn off when you're not using it. :P 

Couldn't find the lock-related config in your dotfiles, so couldn't do a PR. q_q

`i3lock -c 000000` if you're using i3lock.

You'll need to change your dpms settings to let your screens turn off.

**Comment by attente** [comment]
Fixed with https://github.com/attente/dotfiles/commit/6ead5b4b9d8fad80b409fd25370a41d229f2d107 :)
